config/routes.rb
Rails.application.routes.draw do
  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'
  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    validates :body, presence: true, length: { maximum: 300 }
    scope :last_messages, -> { order(:created_at).last(50) }
end

app/models/user.rb
class User < ApplicationRecord
    has_many :messages, dependent: :destroy
    before_save { self.username = username.capitalize }
    validates :username, presence: true, 
                        uniqueness: { case_sensitive: false }, 
                        length: { minimum: 3, maximum: 20 }
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:error] = "You must be logged in to perform that action"
            redirect_to login_path
        end
    end

end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController

    def index
        @message = Message.new
        @messages = Message.last_messages
        @users = User.all
    end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :require_user

    def create
        message = current_user.messages.build(whitelist)
        if message.save
            ActionCable.server.broadcast  "chatroom_channel", {mod_message: message_render(message)}
        end
    end

    private

    def whitelist
        params.require(:message).permit(:body)
    end


    def message_render(message)
        render(partial: 'message', locals: {message: message})
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :logged_in_redirect, only: [:new, :create]

    def new
    end

    def create
        user = User.find_by(username: params[:session][:username].capitalize)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = "Logged in successfully"
            redirect_to root_path
        else
            flash.now[:error] = "There was something wrong with your login details"
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:success] = "You are now logged out"
        redirect_to login_path
    end

    private

    def logged_in_redirect
        if logged_in?
            flash[:error] = "You are already logged in"
            redirect_to root_path
        end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(whitelist)
        if @user.save
            session[:user_id] = @user.id
            flash[:success] = "Welcome to Message Me, #{@user.username}. Your account has been successfully created."
            redirect_to root_path
        else
            render 'new'
        end
    end

    private

    def whitelist
        params.require(:user).permit(:username, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<% if logged_in? %>
  <h2 class="ui center aligned icon header">
    <i class="circular teal comments icon"></i>
  </h2>

  <div class="ui two column grid">
    <div class="twelve wide column">
      <div class="ui card fluid raised chatbox">
        <div class="content" id="messages">
          <div class="ui feed" id="message-container">
            <%= render @messages %>
          </div>
        </div>
        <div class="extra content">
          <%= form_for(@message, html: { class:"ui reply form", role: "form" }, url: message_path, remote: true) do |f| %>
            <div class="field">
              <div class="ui fluid transparent icon input">
                <%= f.text_field :body, autocomplete: "off", placeholder: "Type in your message" %>
                <%= f.button '<i class="paper plane icon"></i>'.html_safe, class: "ui icon button teal tiny message-button" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="four wide column ">
      <div class="ui card fluid raised chatbox" id="users-card">
        <div class="ui vertical menu">
          <% @users.each do |user| %>
            <a class="teal item">
              <%= user.username %>
              <div class="ui left pointing label">1</div>
            </a>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <h2 class="ui center aligned icon header">
    <i class="circular teal power off icon"></i>
    <div class="content">Welcome to Message Me</div>
    <div class="sub header">You need to be logged in to use the app</div>
  </h2>
  

  <div class="ui placeholder segment">
    <div class="ui very relaxed stackable grid">
      <div class="column">
        <%= form_for(:session, html: {class: "ui form", role: "form"}, url: login_path) do |f| %>
          <div class="field">
            <%= f.label :username, "Username" %>
            <div class="ui left icon input">
              <%= f.text_field :username, placeholder: "Username" %>
              <i class="user icon"></i>
            </div>
          </div>
          <div class="field">
            <%= f.label :password, "Password" %>
            <div class="ui left icon input">
              <%= f.password_field :password, placeholder: "password" %>
              <i class="lock icon"></i>
            </div>
          </div>
          <%= f.button "Log in", class: "ui teal submit button" %>
        <% end %>
        <div class="ui horizontal divider">
        OR
        </div>
        <a href="<%= signup_path %>" class="ui big button">
          <i class="signup icon"></i>
          Sign Up
        </a>    
      </div>
    </div>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="ui bottom fixed menu footer">
  <a class="item" href="http://sophiebonneval.com/" target="_blank">Copyright © Sophie Bonneval</a>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |type, msg| %>    
    <div class="ui <%= type %> message transition">
      <i class="close icon"></i>
      <div class="header">
        <%= msg %>
      </div>
    </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="ui large menu">
  <div class="ui container">
    <%= link_to "Chatroom", root_path, class: "item teal" %>    
    <a class="item teal">
      Messages
    </a>
    <div class="right menu">
      <% if logged_in? %>
        <div class="ui dropdown item teal" id="nav-dropdown">
          <%= current_user.username %> <i class="dropdown icon"></i>
          <div class="menu">
            <%= link_to "My account", root_path, class: "item teal" %>
            <%= link_to "Logout", logout_path, method: :delete, class: "item teal" %>
          </div>
        </div>
      <% else %>
      <div class="item" id="nav-item">
        <%= link_to "Log in", login_path, class: "ui primary button nav-button" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Messageme</title>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="ui container" id="page-container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="text">
       <strong><%= message.user.username %> :</strong> <%= message.body %>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="ui error message transition center aligned">
    <i class="close icon"></i>
    <h4 class="header">The following errors prevented the <%= obj.class.name.downcase %> to be saved:</h4>
    <ul class="list">        
      <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<h1 class="ui center aligned header">Sign up to use Message Me</h1>

<%= render 'shared/errors', obj: @user %>

<div class="ui placeholder segment">
  <div class="ui very relaxed stackable grid">
    <div class="column">
      <%= form_with(model: @user, local: true, html: {class: "ui form", role: "form"}) do |f| %>
        <div class="field">
          <%= f.label :username, "Username" %>
          <div class="ui left icon input">
            <%= f.text_field :username, placeholder: "Username" %>
            <i class="user icon"></i>
          </div>
        </div>
        <div class="field">
          <%= f.label :password, "Password" %>
          <div class="ui left icon input">
            <%= f.password_field :password, placeholder: "password" %>
            <i class="lock icon"></i>
          </div>
        </div>
        <%= f.button "Sign up", class: "ui teal submit button" %>
      <% end %>
      <div class="ui horizontal divider">
      OR
      </div>
      <a href="<%= login_path %>" class="ui big button">
        <i class="signup icon"></i>
        Log in
      </a>    
    </div>
  </div>
</div>